### ISSUE TITLE
401 Unauthorized Error on login

### ISSUE THREAD

**Issue by ibobcode** [cghdev/gotunl#6]
Hello ! 
First of all, very nice job for coding what everybody wants 🙏🏻

I just have an issue on the login part that maybe you have encountered before :
`{401 Unauthorized 401 HTTP/1.1 1 1 map[Content-Length:[0] Date:[Wed, 12 Aug 2020 10:11:25 GMT]] {} 0 [] false false map[] 0xc00017a000 <nil>}`

This error is occurring on the login request within your makeReq() called from ConnectProfile(). At first, I was just not getting any error message, I was just launching the app, writing my credentials, but noting was happening and no connection was established.
So I just added a little print in your code to see what was going on right there : 
<img width="480" alt="Screen Shot 2020-08-12 at 12 41 16" src="https://user-images.githubusercontent.com/11737196/90006418-1fcf2e80-dc99-11ea-8336-37d90f30f19f.png">
And you saw the result 😬

Any ideas on what could be the problem here ? 🙏🏻

EDIT: I also saw that you are sending this data as request body : 
`{
    "id": "...",
    "reconnect": true,
    "timeout": true,
    "username":"pritunl",
   "password":"789715",
   "data":"..."
}`
Is that normal that my username is pritunl? Shouldn't it be the one contained in my pritunl .conf file ? 🤔

**Comment by cghdev** [comment]
Hi @ibobcode,
What pritunl client version are you using and what operating system?
I assume it works fine when you use Pritunl Client to connect directly from the GUI, right?

**Comment by ibobcode** [comment]
Whoah ! Fast answer haha ! 
Pritunl client : <img width="155" alt="Screen Shot 2020-08-12 at 12 46 16" src="https://user-images.githubusercontent.com/11737196/90006763-d206f600-dc99-11ea-9836-ad24b1506e30.png">
OS : <img width="259" alt="Screen Shot 2020-08-12 at 12 46 41" src="https://user-images.githubusercontent.com/11737196/90006794-e0eda880-dc99-11ea-9515-270974a13444.png">

And yep, everything works fine when using GUI client ✅

**Comment by cghdev** [comment]
Could you try to install the latest [Pritunl Client](https://github.com/pritunl/pritunl-client-electron/releases/download/1.0.2440.93/Pritunl.pkg.zip) version?
Haven't seen that problem before. The only http connections gotunl makes are locally to the pritunl service (in the past to a local port via http, now it does it to a unix socket both for linux and macOS)

**Comment by ibobcode** [comment]
Hell yeah it's working ! Thank you for the efficient problem solving !! 🔥
